import Title from "@/components/title";


export default function Home() {
  return (
    <main>
      <section id="inicio">
        <Title>Início</Title>
        <p>
          <p>Lorem ipsum dolor sit amet. Qui possimus placeat et nostrum aspernatur non veniam blanditiis id unde asperiores nam dicta sint. Rem quas animi et laudantium eius ea ipsam odit At consequatur voluptates aut aspernatur molestiae aut ratione incidunt. </p><p>Sed cumque omnis ut cumque aspernatur et impedit optio ut voluptatibus voluptatibus et atque dolore. Qui exercitationem asperiores aut sint recusandae sit repellat repellendus et soluta quod et voluptatem excepturi id sunt quaerat rem animi mollitia. </p><p>Id dignissimos earum aut officiis quia in debitis internos sit sequi sequi quo commodi omnis. Aut perferendis quas ea voluptatem doloribus et galisum commodi et dolor cumque et porro nemo a consequatur amet et eligendi impedit. </p><p>Et facilis inventore in molestias dignissimos et quae error ea corporis excepturi. At nisi quia qui veritatis officia sed commodi maiores. </p><p>Quo laboriosam nostrum in aperiam asperiores et adipisci quibusdam ab fugit quia. Ea earum perspiciatis quo harum porro At reiciendis voluptatem sit vero error ut adipisci omnis aut voluptas necessitatibus. </p><p>Est laboriosam maxime est accusantium omnis est corrupti numquam ut galisum voluptate id provident quas! Nam voluptate fugit et atque facilis eos possimus nobis. </p><p>Et facere doloremque aut deserunt culpa eum consectetur reprehenderit sed magni iste. Sed aperiam sapiente vel officiis similique et modi voluptatem qui magni maiores 33 quia labore qui harum voluptate. Ea quia voluptas ea natus quia ea voluptatem expedita rem quia autem est odit voluptas et blanditiis dolores. Ab excepturi omnis est iure quam et rerum repellendus hic illum alias. </p><p>Eos dignissimos aliquam et nisi deleniti id alias ullam. Ex repudiandae reiciendis ut impedit libero eos galisum ipsa. Est tempora laboriosam nam quod voluptas At minima suscipit. </p><p>Non sint illum hic possimus mollitia est possimus repellendus et rerum facere sed quidem rerum. Et corporis quam ut iusto internos quo quasi itaque non autem perspiciatis et modi voluptates? Est aspernatur animi et consequatur facere qui omnis nulla qui quasi voluptate aut alias officia ad consequuntur velit et dolor iure. Ut soluta tempora quo tempore perspiciatis qui assumenda amet cum natus minus. </p><p>Qui voluptas dolorem aut ipsa odit a repellendus consequatur qui voluptatibus voluptas et dolores numquam qui suscipit rerum et consequatur molestias? Sed sapiente minus ut autem aperiam in iusto optio ut voluptatem adipisci At corporis inventore. </p>

        </p>
      </section>

      <section id="projetos">
        <Title>Projeos</Title>
        <p>
          <p>Lorem ipsum dolor sit amet. Qui possimus placeat et nostrum aspernatur non veniam blanditiis id unde asperiores nam dicta sint. Rem quas animi et laudantium eius ea ipsam odit At consequatur voluptates aut aspernatur molestiae aut ratione incidunt. </p><p>Sed cumque omnis ut cumque aspernatur et impedit optio ut voluptatibus voluptatibus et atque dolore. Qui exercitationem asperiores aut sint recusandae sit repellat repellendus et soluta quod et voluptatem excepturi id sunt quaerat rem animi mollitia. </p><p>Id dignissimos earum aut officiis quia in debitis internos sit sequi sequi quo commodi omnis. Aut perferendis quas ea voluptatem doloribus et galisum commodi et dolor cumque et porro nemo a consequatur amet et eligendi impedit. </p><p>Et facilis inventore in molestias dignissimos et quae error ea corporis excepturi. At nisi quia qui veritatis officia sed commodi maiores. </p><p>Quo laboriosam nostrum in aperiam asperiores et adipisci quibusdam ab fugit quia. Ea earum perspiciatis quo harum porro At reiciendis voluptatem sit vero error ut adipisci omnis aut voluptas necessitatibus. </p><p>Est laboriosam maxime est accusantium omnis est corrupti numquam ut galisum voluptate id provident quas! Nam voluptate fugit et atque facilis eos possimus nobis. </p><p>Et facere doloremque aut deserunt culpa eum consectetur reprehenderit sed magni iste. Sed aperiam sapiente vel officiis similique et modi voluptatem qui magni maiores 33 quia labore qui harum voluptate. Ea quia voluptas ea natus quia ea voluptatem expedita rem quia autem est odit voluptas et blanditiis dolores. Ab excepturi omnis est iure quam et rerum repellendus hic illum alias. </p><p>Eos dignissimos aliquam et nisi deleniti id alias ullam. Ex repudiandae reiciendis ut impedit libero eos galisum ipsa. Est tempora laboriosam nam quod voluptas At minima suscipit. </p><p>Non sint illum hic possimus mollitia est possimus repellendus et rerum facere sed quidem rerum. Et corporis quam ut iusto internos quo quasi itaque non autem perspiciatis et modi voluptates? Est aspernatur animi et consequatur facere qui omnis nulla qui quasi voluptate aut alias officia ad consequuntur velit et dolor iure. Ut soluta tempora quo tempore perspiciatis qui assumenda amet cum natus minus. </p><p>Qui voluptas dolorem aut ipsa odit a repellendus consequatur qui voluptatibus voluptas et dolores numquam qui suscipit rerum et consequatur molestias? Sed sapiente minus ut autem aperiam in iusto optio ut voluptatem adipisci At corporis inventore. </p>

        </p>
      </section>

      <section id="videos">
        <Title>Videos</Title>
        <p>
          <p>Lorem ipsum dolor sit amet. Qui possimus placeat et nostrum aspernatur non veniam blanditiis id unde asperiores nam dicta sint. Rem quas animi et laudantium eius ea ipsam odit At consequatur voluptates aut aspernatur molestiae aut ratione incidunt. </p><p>Sed cumque omnis ut cumque aspernatur et impedit optio ut voluptatibus voluptatibus et atque dolore. Qui exercitationem asperiores aut sint recusandae sit repellat repellendus et soluta quod et voluptatem excepturi id sunt quaerat rem animi mollitia. </p><p>Id dignissimos earum aut officiis quia in debitis internos sit sequi sequi quo commodi omnis. Aut perferendis quas ea voluptatem doloribus et galisum commodi et dolor cumque et porro nemo a consequatur amet et eligendi impedit. </p><p>Et facilis inventore in molestias dignissimos et quae error ea corporis excepturi. At nisi quia qui veritatis officia sed commodi maiores. </p><p>Quo laboriosam nostrum in aperiam asperiores et adipisci quibusdam ab fugit quia. Ea earum perspiciatis quo harum porro At reiciendis voluptatem sit vero error ut adipisci omnis aut voluptas necessitatibus. </p><p>Est laboriosam maxime est accusantium omnis est corrupti numquam ut galisum voluptate id provident quas! Nam voluptate fugit et atque facilis eos possimus nobis. </p><p>Et facere doloremque aut deserunt culpa eum consectetur reprehenderit sed magni iste. Sed aperiam sapiente vel officiis similique et modi voluptatem qui magni maiores 33 quia labore qui harum voluptate. Ea quia voluptas ea natus quia ea voluptatem expedita rem quia autem est odit voluptas et blanditiis dolores. Ab excepturi omnis est iure quam et rerum repellendus hic illum alias. </p><p>Eos dignissimos aliquam et nisi deleniti id alias ullam. Ex repudiandae reiciendis ut impedit libero eos galisum ipsa. Est tempora laboriosam nam quod voluptas At minima suscipit. </p><p>Non sint illum hic possimus mollitia est possimus repellendus et rerum facere sed quidem rerum. Et corporis quam ut iusto internos quo quasi itaque non autem perspiciatis et modi voluptates? Est aspernatur animi et consequatur facere qui omnis nulla qui quasi voluptate aut alias officia ad consequuntur velit et dolor iure. Ut soluta tempora quo tempore perspiciatis qui assumenda amet cum natus minus. </p><p>Qui voluptas dolorem aut ipsa odit a repellendus consequatur qui voluptatibus voluptas et dolores numquam qui suscipit rerum et consequatur molestias? Sed sapiente minus ut autem aperiam in iusto optio ut voluptatem adipisci At corporis inventore. </p>

        </p>
      </section>
    </main>
  );
}
